-- schema.sql — SAFE VERSION (NO DROP, NO TRUNCATE)

CREATE TABLE IF NOT EXISTS system_admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(50),
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(500),
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(50),
    position VARCHAR(50) NOT NULL,
    join_date DATE NOT NULL,
    department_id BIGINT,
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),

    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line1 VARCHAR(255),
    line2 VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    pin_code VARCHAR(20),
    country VARCHAR(100),
    type VARCHAR(50) NOT NULL,
    employee_id BIGINT,
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),

    CONSTRAINT fk_address_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

















--
--DROP TABLE IF EXISTS addresses CASCADE;
--DROP TABLE IF EXISTS employees CASCADE;
--DROP TABLE IF EXISTS departments CASCADE;
--DROP TABLE IF EXISTS system_admins CASCADE;
--
--CREATE TABLE system_admins (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    username VARCHAR(100) NOT NULL UNIQUE,
--    email VARCHAR(255) NOT NULL UNIQUE,
--    phone VARCHAR(50),
--    password VARCHAR(255) NOT NULL,
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    created_by VARCHAR(255),
--    updated_at TIMESTAMP,
--    updated_by VARCHAR(255)
--);
--
--CREATE TABLE departments (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    name VARCHAR(255) NOT NULL UNIQUE,
--    description VARCHAR(500),
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    created_by VARCHAR(255),
--    updated_at TIMESTAMP,
--    updated_by VARCHAR(255)
--);
--
--CREATE TABLE employees (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    first_name VARCHAR(255) NOT NULL,
--    last_name VARCHAR(255),
--    email VARCHAR(255) NOT NULL UNIQUE,
--    phone VARCHAR(50),
--    position VARCHAR(50) NOT NULL,
--    join_date DATE NOT NULL,
--    department_id BIGINT,
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    created_by VARCHAR(255),
--    updated_at TIMESTAMP,
--    updated_by VARCHAR(255),
--    CONSTRAINT fk_employee_department
--        FOREIGN KEY (department_id)
--        REFERENCES departments(id)
--        ON DELETE SET NULL
--);
--
--CREATE TABLE addresses (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    line1 VARCHAR(255),
--    line2 VARCHAR(255),
--    city VARCHAR(100),
--    state VARCHAR(100),
--    pin_code VARCHAR(20),
--    country VARCHAR(100),
--    type VARCHAR(50) NOT NULL,
--    employee_id BIGINT,
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    created_by VARCHAR(255),
--    updated_at TIMESTAMP,
--    updated_by VARCHAR(255),
--    CONSTRAINT fk_address_employee
--        FOREIGN KEY (employee_id)
--        REFERENCES employees(id)
--        ON DELETE CASCADE
--);

